apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nats-server-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-server-operator
  template:
    spec:
      containers:
      - args: ["-D", "-V"]
        image: wallyqs/nats-server-operator:latest
        name: nats-server-operator
