---
apiVersion: nats.io/v1alpha3
kind: NatsCluster
metadata:
  name: demo-nats
spec:
  size: 3
  version: "1.1.0"
  pod:
    enableConfigReload: true
  auth:
    enableServiceAccounts: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-nats-account

---
apiVersion: nats.io/v1alpha3
kind: ServiceRole
metadata:
  name: demo-nats-role
  namespace: default

  # Specifies which NATS cluster will be mapping this account,
  # (have to create a service role with permission per cluster).
  labels:
    nats_cluster: demo-nats
spec:
  serviceAccountName: demo-nats-account
  permissions:
    publish: ["foo.*", "foo.bar.quux"]
    subscribe: ["foo.bar"]

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-nats-ops-10
spec:
  volumes:
    - name: "token"
      projected:
        sources:
        - serviceAccountToken:
            # This has to map to the value in the API Server
            # audience: "nats://demo-nats" # could be the cluster name here then?
            audience: "api"
            path: "token"

  # Instead of this will have to mount a secret named the same
  # and set the name of the account as an environment variable.
  # serviceAccountName: demo-nats-account
  restartPolicy: Never
  containers:
    - name: nats-ops
      command: ["/bin/sh"]
      image: "wallyqs/nats-ops:latest"
      tty: true
      stdin: true
      stdinOnce: true

      # Declare it here in order to have access
      # to the service account.
      volumeMounts:
      - name: "token"
        mountPath: "/var/run/secrets/nats.io"

      # volumeMounts:
      # - name: "token"
      #   mountPath: "/var/run/secrets/nats/token"
      # TODO: This should be a projection
